start https://www.everythingrf.com/
start http://www.radio-electronics.com/info/wireless/
start http://www.marketsandmarkets.com/Market-Reports/wireless-connectivity-market-192605963.html
start http://www.ti.com/lsds/ti/wireless-connectivity/overview.page
start http://www.microchip.com/design-centers/wireless-connectivity
start http://www.st.com/en/wireless-connectivity.html
start http://www.atmel.com/products/wireless/default.aspx
start http://www.nxp.com/products/wireless-connectivity:WIRELESS-CONNECTIVITY
start http://www.cypress.com/products/wireless-connectivity
start https://na.industrial.panasonic.com/products/wireless-connectivity